#!/bin/bash
# postinst script for se3-ocs-clientwin
#
# see: dh_installdeb(1)

set -e



case "$1" in
    install|configure)

. /usr/share/se3/includes/config.inc.sh -svm > /dev/null


if [ "X$xppass" = "X" ]; then # if empty
	echo "pas de mot de pass defini pour adminse3"
	exit 1
fi

##### Gereration du job CPAU cote serveur. ###
OcsDir="/var/se3/Progs/ro/inventory/deploy"
# Fix for wine when running from sudo
export HOME=/root
JOB=cpauOcs.job
WINECMD="env WINEDEBUG=-all wine"
rm -f $OcsDir/$JOB
echo "Creation du $JOB CPAU destine a installer ocs-clientwin sur les postes."
TASK="echo Veuillez patienter...&&c:\\tmpOcs\\OcsAgentSetup.exe /S /server:$se3ip /pnum:909 /np /debug"
echo "TASK se3 : $TASK" | sed -e "s/$xppass/XXXXXX/g"
cd /tmp
$WINECMD /home/netlogon/CPAU.exe -u adminse3 -wait  -p $xppass -file $JOB -lwop  -c -ex "$TASK" -enc > /dev/null
mv $JOB $OcsDir


### CREATION DE ocs.bat cote serveur pour les postes Clients W98 ou WinXP ###
echo "Modification de $OcsDir/ocs.bat"


#### AJOUT DE LA LIGNE DANS base/logon.bat #####
if [ "$(cat /home/templates/base/logon.bat | grep "ocs.bat")" = "" ]; then
	echo "Ajout de la ligne necessaire dans /home/templates/base/logon.bat"
	echo " A Faire"
	echo -e "\r">>/home/templates/base/logon.bat
	DEBVERS=$(cat /etc/debian_version)
# 	if [ "$DEBVERS" == "4.0" ]; then
# 		echo -e "::call \\\\\\\\$netbios_name\\Progs\\\\ro\\inventory\\deploy\\ocs.bat\r">>/home/templates/base/logon.bat
# 	else
# 		echo -e "call \\\\\\\\$netbios_name\\Progs\\\\ro\\inventory\\deploy\\ocs.bat\r">>/home/templates/base/logon.bat
# 	fi
else
	echo "Nettoyage de l'ancienne version se3-ocs-clientwin."
	echo " A Faire"
fi

#### DROITS SUR Progs ####
echo "Positionnement correct des droits sur le dossier de deploiement."
chown -R admin:admins /var/se3/Progs/ro/inventory
setfacl -R -m m:rwx /var/se3/Progs/ro/inventory


echo "Configuration de se3-ocs-clientwin terminee."

;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
