#!/bin/bash
# postinst script for se3-ocs-clientwin
#
# see: dh_installdeb(1)

set -e

case "$1" in
    install|configure)

. /usr/share/se3/includes/config.inc.sh -svm > /dev/null


if [ "X$xppass" = "X" ]; then # if empty
	echo "pas de mot de pass defini pour adminse3"
	exit 1
fi


##### Grand nettoyage des versions précédentes de ocs #####
if [ -e /var/se3/Progs/install/ocs-config.bat ]; then
	echo "Suppression de ocs-config.bat devenu inutile."
	rm -rf /var/se3/Progs/install/ocs-config.bat
fi
if [ -e /var/se3/Progs/ro/inventory/deploy/cpauOcs.job ]; then
	echo "Suppression de cpauOcs.job devenu inutile."
	rm -rf /var/se3/Progs/ro/inventory/deploy/cpauOcs.job
fi
if [ -e /var/se3/Progs/ro/inventory/deploy/ocsremontee.bat ]; then
	echo "Suppression de ocsremontee.bat devenu inutile."
	rm -rf /var/se3/Progs/ro/inventory/deploy/ocsremontee.bat
fi
if [ -e /var/se3/Progs/ro/inventory/deploy/cpauOcsRemontee.job ]; then
	echo "Suppression de cpauOcsRemontee.job devenu inutile."
	rm -rf /var/se3/Progs/ro/inventory/deploy/cpauOcsRemontee.job
fi


##### Gereration du job CPAU cote serveur. ###
OcsDir="/var/se3/Progs/ro/inventory/deploy"
Ocsbat="$OcsDir/ocs.bat"
Ocsautonomebat="$OcsDir/ocs_autonome.bat"

# Fix for wine when running from sudo
export HOME=/root
JOB=cpauOcs.job
JOB2=cpauOcs2.job
WINECMD="env WINEDEBUG=-all wine"

##### Generation du job CPAU install. ###
rm -f $OcsDir/$JOB
echo "Creation du $JOB CPAU destine a installer ocs-clientwin sur tous les postes."
TASK="call \\\\$netbios_name\\Progs\\ro\\inventory\\deploy\\ocs.bat";
echo "TASK se3 : $TASK" | sed -e "s/$xppass/XXXXXX/g"
cd /tmp
$WINECMD /home/netlogon/CPAU.exe -u adminse3 -wait  -p $xppass -file $JOB -lwp  -c -ex "$TASK" -enc > /dev/null
mv $JOB $OcsDir

##### Generation du job CPAU demarrage. ###
rm -f $OcsDir/$JOB2
echo "Creation du $JOB CPAU destine a installer le script sur tous les postes."
TASK="call \\\\$netbios_name\\Progs\\ro\\inventory\\deploy\\ocs_install.bat";
echo "TASK se3 : $TASK" | sed -e "s/$xppass/XXXXXX/g"
cd /tmp
$WINECMD /home/netlogon/CPAU.exe -u adminse3 -wait  -p $xppass -file $JOB2 -lwp  -c -ex "$TASK" -enc > /dev/null
mv $JOB2 $OcsDir

LogonBat="\\\\$netbios_name\\admhomes\\templates\\base\\logon.bat"
### CREATION DE ocs.bat cote serveur pour les postes Windows XP a 10 ###
echo "Modification de $OcsDir/ocs.bat"
sed -i $Ocsbat -e "s/##SE3IP##/${se3ip}/g"
sed -i $Ocsbat -e "s/##NETBIOSNAME##/${netbios_name}/g"

### CREATION DE ocs_autonome.bat cote serveur pour les postes Windows XP a 10 hors SE3 ###
echo "Modification de $OcsDir/ocs_autonome.bat"
sed -i $Ocsautonomebat -e "s/##SE3IP##/${se3ip}/g"
sed -i $Ocsautonomebat -e "s/##NETBIOSNAME##/${netbios_name}/g"

echo "Modification (si besoin) du script de login de base"

# Nettoyage ancienne commande
sed -i "/ocs.bat/d" /home/templates/base/logon.bat
sed -i "/cpauOcs.job/d" /home/templates/base/logon.bat

# Commande a placer dans le script de logon.bat des utilisateurs
FINDCMD="\\\\\\\\$netbios_name\\\\netlogon\\\\CPAU.exe -dec -lwp -hide -wait -cwd %SystemDrive%\\\\ -file \\\\\\\\$netbios_name\\\\Progs\\\\ro\\\\inventory\\\\deploy\\\\$JOB2 2>NUL >NUL"

TEST=""
echo "Commande d'installation de ocs ajoutee a /home/templates/base/logon.bat"
echo "\\\\$netbios_name\\netlogon\\CPAU.exe -dec -lwp -hide -wait -cwd %SystemDrive%\\ -file \\\\$netbios_name\\Progs\\ro\\inventory\\deploy\\$JOB2 2>NUL >NUL">>/home/templates/base/logon.bat
todos /home/templates/base/logon.bat
chown admin:admins /home/templates/base/logon.bat
chmod 770 /home/templates/base/logon.bat

# Commande a placer dans le script de ocsdeploy.bat des utilisateurs
FINDCMD="\\\\\\\\$netbios_name\\\\netlogon\\\\CPAU.exe -dec -lwp -hide -wait -cwd %SystemDrive%\\\\ -file \\\\\\\\$netbios_name\\\\Progs\\\\ro\\\\inventory\\\\deploy\\\\$JOB 2>NUL >NUL"

TEST=""
echo "Commande d'installation de ocs ajoutee a /var/se3/Progs/ro/inventory/deploy/ocsdeploy.bat"
echo "\\\\$netbios_name\\netlogon\\CPAU.exe -dec -lwp -hide -wait -cwd %SystemDrive%\\ -file \\\\$netbios_name\\Progs\\ro\\inventory\\deploy\\$JOB 2>NUL >NUL">>/var/se3/Progs/ro/inventory/deploy/ocsdeploy.bat
todos /var/se3/Progs/ro/inventory/deploy/ocsdeploy.bat
chown admin:admins /var/se3/Progs/ro/inventory/deploy/ocsdeploy.bat
chmod 770 /var/se3/Progs/ro/inventory/deploy/ocsdeploy.bat

#### DROITS SUR Progs ####
echo "Positionnement correct des droits sur le dossier de deploiement."
chown -R admin:admins /var/se3/Progs/ro/inventory
setfacl -R -m m:rwx /var/se3/Progs/ro/inventory

echo "Configuration de se3-ocs-clientwin terminee."

;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
